name: Deploy to ec2
on:
  push:
    branches:
      - main
jobs:
  ubuntu-jobs:
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Build and tag Docker image 
      run: |
        docker build -t jerrywise97/periodapp .
     
    - name: Log in to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image to Docker Hub
      run: |
        docker push jerrywise97/periodapp:latest
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_S }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_S }}
          aws-region: us-east-1
          
    - name: Add EC2 private key to SSH agent
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/key-air.pem
          chmod 400 ~/.ssh/key-air.pem
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/key-air.pem

      env:
        secret_db_url: ${{ secrets.ENV_FILE_CONTENT.SECRET_DB_URL}}
        secret_db_username: ${{ secrets.ENV_FILE_CONTENT.SECRET_DB_USERNAME}}
        secret_db_password: ${{ secrets.ENV_FILE_CONTENT.SECRET_DB_PASSWORD}}
        secret_security_jwtExpTime: ${{ secrets.ENV_FILE_CONTENT.SECRET_SECURITY_JWTEXPTIME}}
        secret_security_jwtSecretKey: ${{ secrets.ENV_FILE_CONTENT.SECRET_SECURITY_JWTSECRETKEY}}
    - name: Connect to EC2 instance and deploy
      run: |
          ssh-keyscan -H 54.157.140.149 >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/key-air.pem ec2-user@54.157.140.149 'sudo docker stop periodapp || true && sudo docker rm -f periodapp || true'
          ssh -i ~/.ssh/key-air.pem ec2-user@54.157.140.149 'sudo docker pull jerrywise97/periodapp:latest'
          ssh -i ~/.ssh/key-air.pem ec2-user@54.157.140.149 'sudo docker run -d \
          -e secret_db_url="${{ env.secret_db_url}}" \
          -e secret_db_username="${{ env.secret_db_username}}" \
          -e secret_db_password="${{ env.secret_db_password}}" \
          -e secret_security_jwtExpTime="${{ env.secret_security_jwtExpTime}}" \
          -e secret_security_jwtSecretKey="${{ env.secret_security_jwtSecretKey}}" \
          --name periodapp \
          -p 8890:8890 \
          jerrywise97/periodapp:latest'



        docker run -d \
            -e DB_HOST="${{ env.DB_HOST }}" \
            -e DB_PORT="${{ env.DB_PORT }}" \
            -e DB_USERNAME="${{ env.DB_USERNAME }}" \
            --name your_container_name \
            your_image_name:your_tag
          
